# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numisma', '0003_objeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('juego', models.CharField(choices=[('RECTA_NUMERICA', 'RECTA_NUMERICA'), ('BALANZA', 'BALANZA'), ('ANY', 'ANY')], max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatarBalanza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_balanza', to='numisma.Avatar'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatarRecta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_recta', to='numisma.Avatar'),
        ),
    ]
