# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numisma', '0004_auto_20170417_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'EN_PROGRESO'), ('FINALIZADO', 'FINALIZADO')], max_length=40)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='numisma.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('RECTA_NUMERICA', 'RECTA_NUMERICA'), ('BALANZA', 'BALANZA'), ('RECTA_NUMERICA_COLOR', 'RECTA_NUMERICA_COLOR')], max_length=40)),
                ('tipo', models.CharField(choices=[('M', 'MONEDAS'), ('B', 'BILLETES'), ('2', 'MONEDAS_Y_BILLETES'), ('MIN', 'MINIMO')], max_length=40)),
                ('siguiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='numisma.Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'EN_PROGRESO'), ('FINALIZADO', 'FINALIZADO'), ('BLOQUEADO', 'BLOQUEADO')], max_length=40)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='numisma.Juego')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='numisma.Nivel')),
            ],
        ),
    ]
