# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numisma', '0007_puntaje_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='tipo',
            field=models.CharField(choices=[('M', 'MONEDAS'), ('B', 'BILLETES'), ('2', 'MONEDAS_Y_BILLETES'), ('MIN', 'MINIMO')], default='M', max_length=40),
            preserve_default=False,
        ),
    ]
